/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceChatRouteImport } from './routes/_workspace.chat'
import { Route as WorkspaceGroupRouteImport } from './routes/_workspace.group'
import { Route as WorkspaceInboxRouteImport } from './routes/_workspace.inbox'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as InvitationInvitationIdRouteImport } from './routes/invitation.$invitationId'
import { Route as WorkspaceAgentsIndexRouteImport } from './routes/_workspace.agents.index'
import { Route as WorkspaceAgentsAgentIdRouteImport } from './routes/_workspace.agents.$agentId'
import { Route as WorkspaceChatIndexRouteImport } from './routes/_workspace.chat.index'
import { Route as WorkspaceChatDiscussionIdRouteImport } from './routes/_workspace.chat.$discussionId'
import { Route as WorkspaceGroupIndexRouteImport } from './routes/_workspace.group.index'
import { Route as WorkspaceGroupSectionRouteImport } from './routes/_workspace.group.$section'
import { Route as WorkspaceIdeasIndexRouteImport } from './routes/_workspace.ideas.index'
import { Route as WorkspaceIdeasProposalIdRouteImport } from './routes/_workspace.ideas.$proposalId'
import { Route as WorkspaceIssuesIndexRouteImport } from './routes/_workspace.issues.index'
import { Route as WorkspaceIssuesIssueIdRouteImport } from './routes/_workspace.issues.$issueId'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace.settings.index'
import { Route as WorkspaceSettingsSectionRouteImport } from './routes/_workspace.settings.$section'
import { Route as WorkspaceTripsIndexRouteImport } from './routes/_workspace.trips.index'
import { Route as WorkspaceTripsTripIdRouteImport } from './routes/_workspace.trips.$tripId'
import { Route as WorkspaceAgentsAgentIdIndexRouteImport } from './routes/_workspace.agents.$agentId.index'
import { Route as WorkspaceAgentsAgentIdRunIdRouteImport } from './routes/_workspace.agents.$agentId.$runId'
import { Route as WorkspaceTripsTripIdIndexRouteImport } from './routes/_workspace.trips.$tripId.index'
import { Route as WorkspaceTripsTripIdSectionRouteImport } from './routes/_workspace.trips.$tripId.$section'
import { Route as WorkspaceTripsTripIdIdeasProposalIdRouteImport } from './routes/_workspace.trips.$tripId.ideas.$proposalId'
import { Route as WorkspaceTripsTripIdIdeasProposalIdIndexRouteImport } from './routes/_workspace.trips.$tripId.ideas.$proposalId.index'
import { Route as WorkspaceTripsTripIdIdeasProposalIdViewRouteImport } from './routes/_workspace.trips.$tripId.ideas.$proposalId.$view'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceGroupRoute = WorkspaceGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceInboxRoute = WorkspaceInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const InvitationInvitationIdRoute = InvitationInvitationIdRouteImport.update({
  id: '/invitation/$invitationId',
  path: '/invitation/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAgentsIndexRoute = WorkspaceAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAgentsAgentIdRoute = WorkspaceAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChatIndexRoute = WorkspaceChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceChatRoute,
} as any)
const WorkspaceChatDiscussionIdRoute =
  WorkspaceChatDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => WorkspaceChatRoute,
  } as any)
const WorkspaceGroupIndexRoute = WorkspaceGroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceGroupRoute,
} as any)
const WorkspaceGroupSectionRoute = WorkspaceGroupSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => WorkspaceGroupRoute,
} as any)
const WorkspaceIdeasIndexRoute = WorkspaceIdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIdeasProposalIdRoute =
  WorkspaceIdeasProposalIdRouteImport.update({
    id: '/ideas/$proposalId',
    path: '/ideas/$proposalId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceIssuesIndexRoute = WorkspaceIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIssuesIssueIdRoute = WorkspaceIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRoute,
} as any)
const WorkspaceSettingsSectionRoute =
  WorkspaceSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => WorkspaceSettingsRoute,
  } as any)
const WorkspaceTripsIndexRoute = WorkspaceTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTripsTripIdRoute = WorkspaceTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAgentsAgentIdIndexRoute =
  WorkspaceAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceAgentsAgentIdRoute,
  } as any)
const WorkspaceAgentsAgentIdRunIdRoute =
  WorkspaceAgentsAgentIdRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => WorkspaceAgentsAgentIdRoute,
  } as any)
const WorkspaceTripsTripIdIndexRoute =
  WorkspaceTripsTripIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceTripsTripIdRoute,
  } as any)
const WorkspaceTripsTripIdSectionRoute =
  WorkspaceTripsTripIdSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => WorkspaceTripsTripIdRoute,
  } as any)
const WorkspaceTripsTripIdIdeasProposalIdRoute =
  WorkspaceTripsTripIdIdeasProposalIdRouteImport.update({
    id: '/ideas/$proposalId',
    path: '/ideas/$proposalId',
    getParentRoute: () => WorkspaceTripsTripIdRoute,
  } as any)
const WorkspaceTripsTripIdIdeasProposalIdIndexRoute =
  WorkspaceTripsTripIdIdeasProposalIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceTripsTripIdIdeasProposalIdRoute,
  } as any)
const WorkspaceTripsTripIdIdeasProposalIdViewRoute =
  WorkspaceTripsTripIdIdeasProposalIdViewRouteImport.update({
    id: '/$view',
    path: '/$view',
    getParentRoute: () => WorkspaceTripsTripIdIdeasProposalIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/chat': typeof WorkspaceChatRouteWithChildren
  '/group': typeof WorkspaceGroupRouteWithChildren
  '/inbox': typeof WorkspaceInboxRoute
  '/settings': typeof WorkspaceSettingsRouteWithChildren
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/agents/$agentId': typeof WorkspaceAgentsAgentIdRouteWithChildren
  '/chat/$discussionId': typeof WorkspaceChatDiscussionIdRoute
  '/group/$section': typeof WorkspaceGroupSectionRoute
  '/ideas/$proposalId': typeof WorkspaceIdeasProposalIdRoute
  '/issues/$issueId': typeof WorkspaceIssuesIssueIdRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/trips/$tripId': typeof WorkspaceTripsTripIdRouteWithChildren
  '/agents/': typeof WorkspaceAgentsIndexRoute
  '/chat/': typeof WorkspaceChatIndexRoute
  '/group/': typeof WorkspaceGroupIndexRoute
  '/ideas/': typeof WorkspaceIdeasIndexRoute
  '/issues/': typeof WorkspaceIssuesIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/trips/': typeof WorkspaceTripsIndexRoute
  '/agents/$agentId/$runId': typeof WorkspaceAgentsAgentIdRunIdRoute
  '/trips/$tripId/$section': typeof WorkspaceTripsTripIdSectionRoute
  '/agents/$agentId/': typeof WorkspaceAgentsAgentIdIndexRoute
  '/trips/$tripId/': typeof WorkspaceTripsTripIdIndexRoute
  '/trips/$tripId/ideas/$proposalId': typeof WorkspaceTripsTripIdIdeasProposalIdRouteWithChildren
  '/trips/$tripId/ideas/$proposalId/$view': typeof WorkspaceTripsTripIdIdeasProposalIdViewRoute
  '/trips/$tripId/ideas/$proposalId/': typeof WorkspaceTripsTripIdIdeasProposalIdIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof WorkspaceInboxRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/': typeof WorkspaceIndexRoute
  '/chat/$discussionId': typeof WorkspaceChatDiscussionIdRoute
  '/group/$section': typeof WorkspaceGroupSectionRoute
  '/ideas/$proposalId': typeof WorkspaceIdeasProposalIdRoute
  '/issues/$issueId': typeof WorkspaceIssuesIssueIdRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/agents': typeof WorkspaceAgentsIndexRoute
  '/chat': typeof WorkspaceChatIndexRoute
  '/group': typeof WorkspaceGroupIndexRoute
  '/ideas': typeof WorkspaceIdeasIndexRoute
  '/issues': typeof WorkspaceIssuesIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/trips': typeof WorkspaceTripsIndexRoute
  '/agents/$agentId/$runId': typeof WorkspaceAgentsAgentIdRunIdRoute
  '/trips/$tripId/$section': typeof WorkspaceTripsTripIdSectionRoute
  '/agents/$agentId': typeof WorkspaceAgentsAgentIdIndexRoute
  '/trips/$tripId': typeof WorkspaceTripsTripIdIndexRoute
  '/trips/$tripId/ideas/$proposalId/$view': typeof WorkspaceTripsTripIdIdeasProposalIdViewRoute
  '/trips/$tripId/ideas/$proposalId': typeof WorkspaceTripsTripIdIdeasProposalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/chat': typeof WorkspaceChatRouteWithChildren
  '/_workspace/group': typeof WorkspaceGroupRouteWithChildren
  '/_workspace/inbox': typeof WorkspaceInboxRoute
  '/_workspace/settings': typeof WorkspaceSettingsRouteWithChildren
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/agents/$agentId': typeof WorkspaceAgentsAgentIdRouteWithChildren
  '/_workspace/chat/$discussionId': typeof WorkspaceChatDiscussionIdRoute
  '/_workspace/group/$section': typeof WorkspaceGroupSectionRoute
  '/_workspace/ideas/$proposalId': typeof WorkspaceIdeasProposalIdRoute
  '/_workspace/issues/$issueId': typeof WorkspaceIssuesIssueIdRoute
  '/_workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/_workspace/trips/$tripId': typeof WorkspaceTripsTripIdRouteWithChildren
  '/_workspace/agents/': typeof WorkspaceAgentsIndexRoute
  '/_workspace/chat/': typeof WorkspaceChatIndexRoute
  '/_workspace/group/': typeof WorkspaceGroupIndexRoute
  '/_workspace/ideas/': typeof WorkspaceIdeasIndexRoute
  '/_workspace/issues/': typeof WorkspaceIssuesIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/_workspace/trips/': typeof WorkspaceTripsIndexRoute
  '/_workspace/agents/$agentId/$runId': typeof WorkspaceAgentsAgentIdRunIdRoute
  '/_workspace/trips/$tripId/$section': typeof WorkspaceTripsTripIdSectionRoute
  '/_workspace/agents/$agentId/': typeof WorkspaceAgentsAgentIdIndexRoute
  '/_workspace/trips/$tripId/': typeof WorkspaceTripsTripIdIndexRoute
  '/_workspace/trips/$tripId/ideas/$proposalId': typeof WorkspaceTripsTripIdIdeasProposalIdRouteWithChildren
  '/_workspace/trips/$tripId/ideas/$proposalId/$view': typeof WorkspaceTripsTripIdIdeasProposalIdViewRoute
  '/_workspace/trips/$tripId/ideas/$proposalId/': typeof WorkspaceTripsTripIdIdeasProposalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/group'
    | '/inbox'
    | '/settings'
    | '/invitation/$invitationId'
    | '/agents/$agentId'
    | '/chat/$discussionId'
    | '/group/$section'
    | '/ideas/$proposalId'
    | '/issues/$issueId'
    | '/settings/$section'
    | '/trips/$tripId'
    | '/agents/'
    | '/chat/'
    | '/group/'
    | '/ideas/'
    | '/issues/'
    | '/settings/'
    | '/trips/'
    | '/agents/$agentId/$runId'
    | '/trips/$tripId/$section'
    | '/agents/$agentId/'
    | '/trips/$tripId/'
    | '/trips/$tripId/ideas/$proposalId'
    | '/trips/$tripId/ideas/$proposalId/$view'
    | '/trips/$tripId/ideas/$proposalId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/invitation/$invitationId'
    | '/'
    | '/chat/$discussionId'
    | '/group/$section'
    | '/ideas/$proposalId'
    | '/issues/$issueId'
    | '/settings/$section'
    | '/agents'
    | '/chat'
    | '/group'
    | '/ideas'
    | '/issues'
    | '/settings'
    | '/trips'
    | '/agents/$agentId/$runId'
    | '/trips/$tripId/$section'
    | '/agents/$agentId'
    | '/trips/$tripId'
    | '/trips/$tripId/ideas/$proposalId/$view'
    | '/trips/$tripId/ideas/$proposalId'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/chat'
    | '/_workspace/group'
    | '/_workspace/inbox'
    | '/_workspace/settings'
    | '/invitation/$invitationId'
    | '/_workspace/'
    | '/_workspace/agents/$agentId'
    | '/_workspace/chat/$discussionId'
    | '/_workspace/group/$section'
    | '/_workspace/ideas/$proposalId'
    | '/_workspace/issues/$issueId'
    | '/_workspace/settings/$section'
    | '/_workspace/trips/$tripId'
    | '/_workspace/agents/'
    | '/_workspace/chat/'
    | '/_workspace/group/'
    | '/_workspace/ideas/'
    | '/_workspace/issues/'
    | '/_workspace/settings/'
    | '/_workspace/trips/'
    | '/_workspace/agents/$agentId/$runId'
    | '/_workspace/trips/$tripId/$section'
    | '/_workspace/agents/$agentId/'
    | '/_workspace/trips/$tripId/'
    | '/_workspace/trips/$tripId/ideas/$proposalId'
    | '/_workspace/trips/$tripId/ideas/$proposalId/$view'
    | '/_workspace/trips/$tripId/ideas/$proposalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  InvitationInvitationIdRoute: typeof InvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/chat': {
      id: '/_workspace/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/group': {
      id: '/_workspace/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof WorkspaceGroupRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/inbox': {
      id: '/_workspace/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof WorkspaceInboxRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/invitation/$invitationId': {
      id: '/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/invitation/$invitationId'
      preLoaderRoute: typeof InvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/agents/': {
      id: '/_workspace/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof WorkspaceAgentsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/agents/$agentId': {
      id: '/_workspace/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof WorkspaceAgentsAgentIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/chat/': {
      id: '/_workspace/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof WorkspaceChatIndexRouteImport
      parentRoute: typeof WorkspaceChatRoute
    }
    '/_workspace/chat/$discussionId': {
      id: '/_workspace/chat/$discussionId'
      path: '/$discussionId'
      fullPath: '/chat/$discussionId'
      preLoaderRoute: typeof WorkspaceChatDiscussionIdRouteImport
      parentRoute: typeof WorkspaceChatRoute
    }
    '/_workspace/group/': {
      id: '/_workspace/group/'
      path: '/'
      fullPath: '/group/'
      preLoaderRoute: typeof WorkspaceGroupIndexRouteImport
      parentRoute: typeof WorkspaceGroupRoute
    }
    '/_workspace/group/$section': {
      id: '/_workspace/group/$section'
      path: '/$section'
      fullPath: '/group/$section'
      preLoaderRoute: typeof WorkspaceGroupSectionRouteImport
      parentRoute: typeof WorkspaceGroupRoute
    }
    '/_workspace/ideas/': {
      id: '/_workspace/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof WorkspaceIdeasIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/ideas/$proposalId': {
      id: '/_workspace/ideas/$proposalId'
      path: '/ideas/$proposalId'
      fullPath: '/ideas/$proposalId'
      preLoaderRoute: typeof WorkspaceIdeasProposalIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/issues/': {
      id: '/_workspace/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof WorkspaceIssuesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/issues/$issueId': {
      id: '/_workspace/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof WorkspaceIssuesIssueIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/settings/$section': {
      id: '/_workspace/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof WorkspaceSettingsSectionRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/trips/': {
      id: '/_workspace/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof WorkspaceTripsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/trips/$tripId': {
      id: '/_workspace/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof WorkspaceTripsTripIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/agents/$agentId/': {
      id: '/_workspace/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof WorkspaceAgentsAgentIdIndexRouteImport
      parentRoute: typeof WorkspaceAgentsAgentIdRoute
    }
    '/_workspace/agents/$agentId/$runId': {
      id: '/_workspace/agents/$agentId/$runId'
      path: '/$runId'
      fullPath: '/agents/$agentId/$runId'
      preLoaderRoute: typeof WorkspaceAgentsAgentIdRunIdRouteImport
      parentRoute: typeof WorkspaceAgentsAgentIdRoute
    }
    '/_workspace/trips/$tripId/': {
      id: '/_workspace/trips/$tripId/'
      path: '/'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof WorkspaceTripsTripIdIndexRouteImport
      parentRoute: typeof WorkspaceTripsTripIdRoute
    }
    '/_workspace/trips/$tripId/$section': {
      id: '/_workspace/trips/$tripId/$section'
      path: '/$section'
      fullPath: '/trips/$tripId/$section'
      preLoaderRoute: typeof WorkspaceTripsTripIdSectionRouteImport
      parentRoute: typeof WorkspaceTripsTripIdRoute
    }
    '/_workspace/trips/$tripId/ideas/$proposalId': {
      id: '/_workspace/trips/$tripId/ideas/$proposalId'
      path: '/ideas/$proposalId'
      fullPath: '/trips/$tripId/ideas/$proposalId'
      preLoaderRoute: typeof WorkspaceTripsTripIdIdeasProposalIdRouteImport
      parentRoute: typeof WorkspaceTripsTripIdRoute
    }
    '/_workspace/trips/$tripId/ideas/$proposalId/': {
      id: '/_workspace/trips/$tripId/ideas/$proposalId/'
      path: '/'
      fullPath: '/trips/$tripId/ideas/$proposalId/'
      preLoaderRoute: typeof WorkspaceTripsTripIdIdeasProposalIdIndexRouteImport
      parentRoute: typeof WorkspaceTripsTripIdIdeasProposalIdRoute
    }
    '/_workspace/trips/$tripId/ideas/$proposalId/$view': {
      id: '/_workspace/trips/$tripId/ideas/$proposalId/$view'
      path: '/$view'
      fullPath: '/trips/$tripId/ideas/$proposalId/$view'
      preLoaderRoute: typeof WorkspaceTripsTripIdIdeasProposalIdViewRouteImport
      parentRoute: typeof WorkspaceTripsTripIdIdeasProposalIdRoute
    }
  }
}

interface WorkspaceChatRouteChildren {
  WorkspaceChatDiscussionIdRoute: typeof WorkspaceChatDiscussionIdRoute
  WorkspaceChatIndexRoute: typeof WorkspaceChatIndexRoute
}

const WorkspaceChatRouteChildren: WorkspaceChatRouteChildren = {
  WorkspaceChatDiscussionIdRoute: WorkspaceChatDiscussionIdRoute,
  WorkspaceChatIndexRoute: WorkspaceChatIndexRoute,
}

const WorkspaceChatRouteWithChildren = WorkspaceChatRoute._addFileChildren(
  WorkspaceChatRouteChildren,
)

interface WorkspaceGroupRouteChildren {
  WorkspaceGroupSectionRoute: typeof WorkspaceGroupSectionRoute
  WorkspaceGroupIndexRoute: typeof WorkspaceGroupIndexRoute
}

const WorkspaceGroupRouteChildren: WorkspaceGroupRouteChildren = {
  WorkspaceGroupSectionRoute: WorkspaceGroupSectionRoute,
  WorkspaceGroupIndexRoute: WorkspaceGroupIndexRoute,
}

const WorkspaceGroupRouteWithChildren = WorkspaceGroupRoute._addFileChildren(
  WorkspaceGroupRouteChildren,
)

interface WorkspaceSettingsRouteChildren {
  WorkspaceSettingsSectionRoute: typeof WorkspaceSettingsSectionRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteChildren: WorkspaceSettingsRouteChildren = {
  WorkspaceSettingsSectionRoute: WorkspaceSettingsSectionRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
}

const WorkspaceSettingsRouteWithChildren =
  WorkspaceSettingsRoute._addFileChildren(WorkspaceSettingsRouteChildren)

interface WorkspaceAgentsAgentIdRouteChildren {
  WorkspaceAgentsAgentIdRunIdRoute: typeof WorkspaceAgentsAgentIdRunIdRoute
  WorkspaceAgentsAgentIdIndexRoute: typeof WorkspaceAgentsAgentIdIndexRoute
}

const WorkspaceAgentsAgentIdRouteChildren: WorkspaceAgentsAgentIdRouteChildren =
  {
    WorkspaceAgentsAgentIdRunIdRoute: WorkspaceAgentsAgentIdRunIdRoute,
    WorkspaceAgentsAgentIdIndexRoute: WorkspaceAgentsAgentIdIndexRoute,
  }

const WorkspaceAgentsAgentIdRouteWithChildren =
  WorkspaceAgentsAgentIdRoute._addFileChildren(
    WorkspaceAgentsAgentIdRouteChildren,
  )

interface WorkspaceTripsTripIdIdeasProposalIdRouteChildren {
  WorkspaceTripsTripIdIdeasProposalIdViewRoute: typeof WorkspaceTripsTripIdIdeasProposalIdViewRoute
  WorkspaceTripsTripIdIdeasProposalIdIndexRoute: typeof WorkspaceTripsTripIdIdeasProposalIdIndexRoute
}

const WorkspaceTripsTripIdIdeasProposalIdRouteChildren: WorkspaceTripsTripIdIdeasProposalIdRouteChildren =
  {
    WorkspaceTripsTripIdIdeasProposalIdViewRoute:
      WorkspaceTripsTripIdIdeasProposalIdViewRoute,
    WorkspaceTripsTripIdIdeasProposalIdIndexRoute:
      WorkspaceTripsTripIdIdeasProposalIdIndexRoute,
  }

const WorkspaceTripsTripIdIdeasProposalIdRouteWithChildren =
  WorkspaceTripsTripIdIdeasProposalIdRoute._addFileChildren(
    WorkspaceTripsTripIdIdeasProposalIdRouteChildren,
  )

interface WorkspaceTripsTripIdRouteChildren {
  WorkspaceTripsTripIdSectionRoute: typeof WorkspaceTripsTripIdSectionRoute
  WorkspaceTripsTripIdIndexRoute: typeof WorkspaceTripsTripIdIndexRoute
  WorkspaceTripsTripIdIdeasProposalIdRoute: typeof WorkspaceTripsTripIdIdeasProposalIdRouteWithChildren
}

const WorkspaceTripsTripIdRouteChildren: WorkspaceTripsTripIdRouteChildren = {
  WorkspaceTripsTripIdSectionRoute: WorkspaceTripsTripIdSectionRoute,
  WorkspaceTripsTripIdIndexRoute: WorkspaceTripsTripIdIndexRoute,
  WorkspaceTripsTripIdIdeasProposalIdRoute:
    WorkspaceTripsTripIdIdeasProposalIdRouteWithChildren,
}

const WorkspaceTripsTripIdRouteWithChildren =
  WorkspaceTripsTripIdRoute._addFileChildren(WorkspaceTripsTripIdRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRouteWithChildren
  WorkspaceGroupRoute: typeof WorkspaceGroupRouteWithChildren
  WorkspaceInboxRoute: typeof WorkspaceInboxRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceAgentsAgentIdRoute: typeof WorkspaceAgentsAgentIdRouteWithChildren
  WorkspaceIdeasProposalIdRoute: typeof WorkspaceIdeasProposalIdRoute
  WorkspaceIssuesIssueIdRoute: typeof WorkspaceIssuesIssueIdRoute
  WorkspaceTripsTripIdRoute: typeof WorkspaceTripsTripIdRouteWithChildren
  WorkspaceAgentsIndexRoute: typeof WorkspaceAgentsIndexRoute
  WorkspaceIdeasIndexRoute: typeof WorkspaceIdeasIndexRoute
  WorkspaceIssuesIndexRoute: typeof WorkspaceIssuesIndexRoute
  WorkspaceTripsIndexRoute: typeof WorkspaceTripsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRouteWithChildren,
  WorkspaceGroupRoute: WorkspaceGroupRouteWithChildren,
  WorkspaceInboxRoute: WorkspaceInboxRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceAgentsAgentIdRoute: WorkspaceAgentsAgentIdRouteWithChildren,
  WorkspaceIdeasProposalIdRoute: WorkspaceIdeasProposalIdRoute,
  WorkspaceIssuesIssueIdRoute: WorkspaceIssuesIssueIdRoute,
  WorkspaceTripsTripIdRoute: WorkspaceTripsTripIdRouteWithChildren,
  WorkspaceAgentsIndexRoute: WorkspaceAgentsIndexRoute,
  WorkspaceIdeasIndexRoute: WorkspaceIdeasIndexRoute,
  WorkspaceIssuesIndexRoute: WorkspaceIssuesIndexRoute,
  WorkspaceTripsIndexRoute: WorkspaceTripsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  InvitationInvitationIdRoute: InvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
