/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as http from "../http.js";
import type * as migrations from "../migrations.js";
import type * as modules_ai_hosts from "../modules/ai/hosts.js";
import type * as modules_ai_limits from "../modules/ai/limits.js";
import type * as modules_ai_provider from "../modules/ai/provider.js";
import type * as modules_ai_providers from "../modules/ai/providers.js";
import type * as modules_ai_settings from "../modules/ai/settings.js";
import type * as modules_ai_validators from "../modules/ai/validators.js";
import type * as modules_assistant_agent_index from "../modules/assistant/agent/index.js";
import type * as modules_assistant_agent_instructions from "../modules/assistant/agent/instructions.js";
import type * as modules_assistant_agent_session from "../modules/assistant/agent/session.js";
import type * as modules_assistant_agent_types from "../modules/assistant/agent/types.js";
import type * as modules_assistant_chat_index from "../modules/assistant/chat/index.js";
import type * as modules_assistant_errors_index from "../modules/assistant/errors/index.js";
import type * as modules_assistant_model_index from "../modules/assistant/model/index.js";
import type * as modules_assistant_model_proposals from "../modules/assistant/model/proposals.js";
import type * as modules_assistant_model_thread_access from "../modules/assistant/model/thread/access.js";
import type * as modules_assistant_model_trip_context from "../modules/assistant/model/trip/context.js";
import type * as modules_assistant_model_writes from "../modules/assistant/model/writes.js";
import type * as modules_assistant_runs_functions from "../modules/assistant/runs/functions.js";
import type * as modules_assistant_runs_index from "../modules/assistant/runs/index.js";
import type * as modules_assistant_runs_tracking from "../modules/assistant/runs/tracking.js";
import type * as modules_assistant_screen_index from "../modules/assistant/screen/index.js";
import type * as modules_assistant_standalone_context from "../modules/assistant/standalone/context.js";
import type * as modules_assistant_standalone_execute from "../modules/assistant/standalone/execute.js";
import type * as modules_assistant_standalone_index from "../modules/assistant/standalone/index.js";
import type * as modules_assistant_standalone_session from "../modules/assistant/standalone/session.js";
import type * as modules_assistant_validators_index from "../modules/assistant/validators/index.js";
import type * as modules_auth_auth from "../modules/auth/auth.js";
import type * as modules_auth_workspace from "../modules/auth/workspace.js";
import type * as modules_dev_local from "../modules/dev/local.js";
import type * as modules_dev_populate from "../modules/dev/populate.js";
import type * as modules_dev_reset from "../modules/dev/reset.js";
import type * as modules_dev_targets from "../modules/dev/targets.js";
import type * as modules_dev_trips from "../modules/dev/trips.js";
import type * as modules_discussions_assistant_index from "../modules/discussions/assistant/index.js";
import type * as modules_discussions_assistant_respond from "../modules/discussions/assistant/respond.js";
import type * as modules_discussions_media_index from "../modules/discussions/media/index.js";
import type * as modules_discussions_messages_index from "../modules/discussions/messages/index.js";
import type * as modules_discussions_threads_cleanup from "../modules/discussions/threads/cleanup.js";
import type * as modules_discussions_threads_entity from "../modules/discussions/threads/entity.js";
import type * as modules_discussions_threads_index from "../modules/discussions/threads/index.js";
import type * as modules_discussions_threads_limits from "../modules/discussions/threads/limits.js";
import type * as modules_media_attachments_index from "../modules/media/attachments/index.js";
import type * as modules_media_files_index from "../modules/media/files/index.js";
import type * as modules_media_library_commit from "../modules/media/library/commit.js";
import type * as modules_media_library_index from "../modules/media/library/index.js";
import type * as modules_media_library_validators from "../modules/media/library/validators.js";
import type * as modules_notifications_index from "../modules/notifications/index.js";
import type * as modules_organizations_cleanup from "../modules/organizations/cleanup.js";
import type * as modules_organizations_invitations_index from "../modules/organizations/invitations/index.js";
import type * as modules_references_index from "../modules/references/index.js";
import type * as modules_travel_activities_index from "../modules/travel/activities/index.js";
import type * as modules_travel_activities_timeblocks from "../modules/travel/activities/timeblocks.js";
import type * as modules_travel_covers_destination_index from "../modules/travel/covers/destination/index.js";
import type * as modules_travel_covers_destination_stock from "../modules/travel/covers/destination/stock.js";
import type * as modules_travel_covers_index from "../modules/travel/covers/index.js";
import type * as modules_travel_covers_stock from "../modules/travel/covers/stock.js";
import type * as modules_travel_destinations_index from "../modules/travel/destinations/index.js";
import type * as modules_travel_issues_index from "../modules/travel/issues/index.js";
import type * as modules_travel_issues_rewrite from "../modules/travel/issues/rewrite.js";
import type * as modules_travel_locations_index from "../modules/travel/locations/index.js";
import type * as modules_travel_locations_query from "../modules/travel/locations/query.js";
import type * as modules_travel_packing_apply from "../modules/travel/packing/apply.js";
import type * as modules_travel_packing_index from "../modules/travel/packing/index.js";
import type * as modules_travel_packing_writes from "../modules/travel/packing/writes.js";
import type * as modules_travel_preferences_index from "../modules/travel/preferences/index.js";
import type * as modules_travel_stays_index from "../modules/travel/stays/index.js";
import type * as modules_travel_targets_costkinds from "../modules/travel/targets/costkinds.js";
import type * as modules_travel_targets_index from "../modules/travel/targets/index.js";
import type * as modules_travel_targets_kind from "../modules/travel/targets/kind.js";
import type * as modules_travel_targets_kinds_activity_index from "../modules/travel/targets/kinds/activity/index.js";
import type * as modules_travel_targets_kinds_activity_transfer from "../modules/travel/targets/kinds/activity/transfer.js";
import type * as modules_travel_targets_kinds_attachment_index from "../modules/travel/targets/kinds/attachment/index.js";
import type * as modules_travel_targets_kinds_boundary_transfer from "../modules/travel/targets/kinds/boundary/transfer.js";
import type * as modules_travel_targets_kinds_destination_index from "../modules/travel/targets/kinds/destination/index.js";
import type * as modules_travel_targets_kinds_destination_transfer from "../modules/travel/targets/kinds/destination/transfer.js";
import type * as modules_travel_targets_kinds_index from "../modules/travel/targets/kinds/index.js";
import type * as modules_travel_targets_kinds_stay_index from "../modules/travel/targets/kinds/stay/index.js";
import type * as modules_travel_targets_kinds_trip_index from "../modules/travel/targets/kinds/trip/index.js";
import type * as modules_travel_transfers_index from "../modules/travel/transfers/index.js";
import type * as modules_travel_travelers_index from "../modules/travel/travelers/index.js";
import type * as modules_travel_trips_access from "../modules/travel/trips/access.js";
import type * as modules_travel_trips_commit from "../modules/travel/trips/commit.js";
import type * as modules_travel_trips_costs from "../modules/travel/trips/costs.js";
import type * as modules_travel_trips_ctx from "../modules/travel/trips/ctx.js";
import type * as modules_travel_trips_currencies from "../modules/travel/trips/currencies.js";
import type * as modules_travel_trips_datetime from "../modules/travel/trips/datetime.js";
import type * as modules_travel_trips_index from "../modules/travel/trips/index.js";
import type * as modules_travel_trips_itinerary_fields from "../modules/travel/trips/itinerary/fields.js";
import type * as modules_travel_trips_list from "../modules/travel/trips/list.js";
import type * as modules_travel_trips_normalize from "../modules/travel/trips/normalize.js";
import type * as modules_travel_trips_projection from "../modules/travel/trips/projection.js";
import type * as modules_travel_versions_agent_review_action from "../modules/travel/versions/agent/review/action.js";
import type * as modules_travel_versions_agent_review_index from "../modules/travel/versions/agent/review/index.js";
import type * as modules_travel_versions_agent_title_action from "../modules/travel/versions/agent/title/action.js";
import type * as modules_travel_versions_agent_title_index from "../modules/travel/versions/agent/title/index.js";
import type * as modules_travel_versions_apply from "../modules/travel/versions/apply.js";
import type * as modules_travel_versions_clone from "../modules/travel/versions/clone.js";
import type * as modules_travel_versions_content from "../modules/travel/versions/content.js";
import type * as modules_travel_versions_detailrebase from "../modules/travel/versions/detailrebase.js";
import type * as modules_travel_versions_detailresolution from "../modules/travel/versions/detailresolution.js";
import type * as modules_travel_versions_diff from "../modules/travel/versions/diff.js";
import type * as modules_travel_versions_errors from "../modules/travel/versions/errors.js";
import type * as modules_travel_versions_fields_index from "../modules/travel/versions/fields/index.js";
import type * as modules_travel_versions_git_action from "../modules/travel/versions/git/action.js";
import type * as modules_travel_versions_git_index from "../modules/travel/versions/git/index.js";
import type * as modules_travel_versions_index from "../modules/travel/versions/index.js";
import type * as modules_travel_versions_merge_action from "../modules/travel/versions/merge/action.js";
import type * as modules_travel_versions_names from "../modules/travel/versions/names.js";
import type * as modules_travel_versions_presentation from "../modules/travel/versions/presentation.js";
import type * as modules_travel_versions_resolution from "../modules/travel/versions/resolution.js";
import type * as modules_travel_versions_settings from "../modules/travel/versions/settings.js";
import type * as modules_travel_versions_snapshot_format from "../modules/travel/versions/snapshot/format.js";
import type * as modules_travel_versions_snapshot_index from "../modules/travel/versions/snapshot/index.js";
import type * as modules_travel_versions_snapshot_types from "../modules/travel/versions/snapshot/types.js";
import type * as modules_travel_versions_validators from "../modules/travel/versions/validators.js";
import type * as modules_travel_versions_workflow from "../modules/travel/versions/workflow.js";
import type * as routes_agents_get from "../routes/agents/get.js";
import type * as routes_agents_issues from "../routes/agents/issues.js";
import type * as routes_agents_list from "../routes/agents/list.js";
import type * as routes_agents_runs_events from "../routes/agents/runs/events.js";
import type * as routes_agents_runs_get from "../routes/agents/runs/get.js";
import type * as routes_agents_runs_issue from "../routes/agents/runs/issue.js";
import type * as routes_agents_runs_list from "../routes/agents/runs/list.js";
import type * as routes_agents_runs_retry from "../routes/agents/runs/retry.js";
import type * as routes_agents_runs_start from "../routes/agents/runs/start.js";
import type * as routes_agents_runs_stop from "../routes/agents/runs/stop.js";
import type * as routes_agents_runs_workspace from "../routes/agents/runs/workspace.js";
import type * as routes_assistant_chats_create from "../routes/assistant/chats/create.js";
import type * as routes_assistant_chats_list from "../routes/assistant/chats/list.js";
import type * as routes_assistant_chats_tags from "../routes/assistant/chats/tags.js";
import type * as routes_assistant_context_catalog from "../routes/assistant/context/catalog.js";
import type * as routes_assistant_context_screen from "../routes/assistant/context/screen.js";
import type * as routes_assistant_messages from "../routes/assistant/messages.js";
import type * as routes_assistant_open from "../routes/assistant/open.js";
import type * as routes_assistant_resend from "../routes/assistant/resend.js";
import type * as routes_assistant_send from "../routes/assistant/send.js";
import type * as routes_assistant_stop from "../routes/assistant/stop.js";
import type * as routes_dev_reset from "../routes/dev/reset.js";
import type * as routes_discussions_create from "../routes/discussions/create.js";
import type * as routes_discussions_list from "../routes/discussions/list.js";
import type * as routes_discussions_mark_read from "../routes/discussions/mark/read.js";
import type * as routes_discussions_messages_attachments from "../routes/discussions/messages/attachments.js";
import type * as routes_discussions_messages_edit from "../routes/discussions/messages/edit.js";
import type * as routes_discussions_messages_list from "../routes/discussions/messages/list.js";
import type * as routes_discussions_messages_react from "../routes/discussions/messages/react.js";
import type * as routes_discussions_messages_reactions from "../routes/discussions/messages/reactions.js";
import type * as routes_discussions_messages_remove from "../routes/discussions/messages/remove.js";
import type * as routes_discussions_messages_respond from "../routes/discussions/messages/respond.js";
import type * as routes_discussions_messages_send from "../routes/discussions/messages/send.js";
import type * as routes_discussions_messages_stop from "../routes/discussions/messages/stop.js";
import type * as routes_discussions_rename from "../routes/discussions/rename.js";
import type * as routes_discussions_roster from "../routes/discussions/roster.js";
import type * as routes_media_list from "../routes/media/list.js";
import type * as routes_media_logo_clear from "../routes/media/logo/clear.js";
import type * as routes_media_logo_set from "../routes/media/logo/set.js";
import type * as routes_media_remove from "../routes/media/remove.js";
import type * as routes_media_save from "../routes/media/save.js";
import type * as routes_media_upload from "../routes/media/upload.js";
import type * as routes_notifications_list from "../routes/notifications/list.js";
import type * as routes_notifications_mark_all from "../routes/notifications/mark/all.js";
import type * as routes_notifications_mark_read from "../routes/notifications/mark/read.js";
import type * as routes_organizations_invitations_create from "../routes/organizations/invitations/create.js";
import type * as routes_organizations_invitations_list from "../routes/organizations/invitations/list.js";
import type * as routes_organizations_invitations_redeem from "../routes/organizations/invitations/redeem.js";
import type * as routes_organizations_invitations_revoke from "../routes/organizations/invitations/revoke.js";
import type * as routes_references_resolve from "../routes/references/resolve.js";
import type * as routes_settings_ai_get from "../routes/settings/ai/get.js";
import type * as routes_settings_ai_set from "../routes/settings/ai/set.js";
import type * as routes_settings_reviews_get from "../routes/settings/reviews/get.js";
import type * as routes_settings_reviews_set from "../routes/settings/reviews/set.js";
import type * as routes_trips_archive from "../routes/trips/archive.js";
import type * as routes_trips_attachments_list from "../routes/trips/attachments/list.js";
import type * as routes_trips_attachments_set from "../routes/trips/attachments/set.js";
import type * as routes_trips_cover from "../routes/trips/cover.js";
import type * as routes_trips_cover_retry from "../routes/trips/cover/retry.js";
import type * as routes_trips_covers_ensure from "../routes/trips/covers/ensure.js";
import type * as routes_trips_create from "../routes/trips/create.js";
import type * as routes_trips_destinations_activities_add from "../routes/trips/destinations/activities/add.js";
import type * as routes_trips_destinations_activities_remove from "../routes/trips/destinations/activities/remove.js";
import type * as routes_trips_destinations_activities_reorder from "../routes/trips/destinations/activities/reorder.js";
import type * as routes_trips_destinations_activities_transfers_remove from "../routes/trips/destinations/activities/transfers/remove.js";
import type * as routes_trips_destinations_activities_transfers_set from "../routes/trips/destinations/activities/transfers/set.js";
import type * as routes_trips_destinations_activities_update from "../routes/trips/destinations/activities/update.js";
import type * as routes_trips_destinations_add from "../routes/trips/destinations/add.js";
import type * as routes_trips_destinations_covers_ensure from "../routes/trips/destinations/covers/ensure.js";
import type * as routes_trips_destinations_move from "../routes/trips/destinations/move.js";
import type * as routes_trips_destinations_remove from "../routes/trips/destinations/remove.js";
import type * as routes_trips_destinations_stays_add from "../routes/trips/destinations/stays/add.js";
import type * as routes_trips_destinations_stays_remove from "../routes/trips/destinations/stays/remove.js";
import type * as routes_trips_destinations_stays_update from "../routes/trips/destinations/stays/update.js";
import type * as routes_trips_destinations_transfers_remove from "../routes/trips/destinations/transfers/remove.js";
import type * as routes_trips_destinations_transfers_set from "../routes/trips/destinations/transfers/set.js";
import type * as routes_trips_destinations_update from "../routes/trips/destinations/update.js";
import type * as routes_trips_find from "../routes/trips/find.js";
import type * as routes_trips_get from "../routes/trips/get.js";
import type * as routes_trips_issues_assign from "../routes/trips/issues/assign.js";
import type * as routes_trips_issues_comment from "../routes/trips/issues/comment.js";
import type * as routes_trips_issues_create from "../routes/trips/issues/create.js";
import type * as routes_trips_issues_due from "../routes/trips/issues/due.js";
import type * as routes_trips_issues_get from "../routes/trips/issues/get.js";
import type * as routes_trips_issues_list from "../routes/trips/issues/list.js";
import type * as routes_trips_issues_status from "../routes/trips/issues/status.js";
import type * as routes_trips_issues_workspace_list from "../routes/trips/issues/workspace/list.js";
import type * as routes_trips_list from "../routes/trips/list.js";
import type * as routes_trips_locations_nearest from "../routes/trips/locations/nearest.js";
import type * as routes_trips_locations_region from "../routes/trips/locations/region.js";
import type * as routes_trips_packing_add from "../routes/trips/packing/add.js";
import type * as routes_trips_packing_list from "../routes/trips/packing/list.js";
import type * as routes_trips_packing_remove from "../routes/trips/packing/remove.js";
import type * as routes_trips_packing_update from "../routes/trips/packing/update.js";
import type * as routes_trips_preferences_favorite from "../routes/trips/preferences/favorite.js";
import type * as routes_trips_restore from "../routes/trips/restore.js";
import type * as routes_trips_seed_populate from "../routes/trips/seed/populate.js";
import type * as routes_trips_seed_workspace from "../routes/trips/seed/workspace.js";
import type * as routes_trips_transfers_remove from "../routes/trips/transfers/remove.js";
import type * as routes_trips_transfers_set from "../routes/trips/transfers/set.js";
import type * as routes_trips_travelers_claim from "../routes/trips/travelers/claim.js";
import type * as routes_trips_travelers_list from "../routes/trips/travelers/list.js";
import type * as routes_trips_travelers_set from "../routes/trips/travelers/set.js";
import type * as routes_trips_update from "../routes/trips/update.js";
import type * as routes_trips_upload from "../routes/trips/upload.js";
import type * as routes_trips_versions_approval from "../routes/trips/versions/approval.js";
import type * as routes_trips_versions_close from "../routes/trips/versions/close.js";
import type * as routes_trips_versions_create from "../routes/trips/versions/create.js";
import type * as routes_trips_versions_details_resolve from "../routes/trips/versions/details/resolve.js";
import type * as routes_trips_versions_feedback_add from "../routes/trips/versions/feedback/add.js";
import type * as routes_trips_versions_feedback_list from "../routes/trips/versions/feedback/list.js";
import type * as routes_trips_versions_feedback_resolve from "../routes/trips/versions/feedback/resolve.js";
import type * as routes_trips_versions_get from "../routes/trips/versions/get.js";
import type * as routes_trips_versions_list from "../routes/trips/versions/list.js";
import type * as routes_trips_versions_merge from "../routes/trips/versions/merge.js";
import type * as routes_trips_versions_rebase from "../routes/trips/versions/rebase.js";
import type * as routes_trips_versions_resolve from "../routes/trips/versions/resolve.js";
import type * as routes_trips_versions_reviewers_agent_run from "../routes/trips/versions/reviewers/agent/run.js";
import type * as routes_trips_versions_reviewers_set from "../routes/trips/versions/reviewers/set.js";
import type * as routes_trips_versions_submit from "../routes/trips/versions/submit.js";
import type * as routes_trips_versions_workspace_list from "../routes/trips/versions/workspace/list.js";
import type * as routes_trips_versions_workspace_pending from "../routes/trips/versions/workspace/pending.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  http: typeof http;
  migrations: typeof migrations;
  "modules/ai/hosts": typeof modules_ai_hosts;
  "modules/ai/limits": typeof modules_ai_limits;
  "modules/ai/provider": typeof modules_ai_provider;
  "modules/ai/providers": typeof modules_ai_providers;
  "modules/ai/settings": typeof modules_ai_settings;
  "modules/ai/validators": typeof modules_ai_validators;
  "modules/assistant/agent/index": typeof modules_assistant_agent_index;
  "modules/assistant/agent/instructions": typeof modules_assistant_agent_instructions;
  "modules/assistant/agent/session": typeof modules_assistant_agent_session;
  "modules/assistant/agent/types": typeof modules_assistant_agent_types;
  "modules/assistant/chat/index": typeof modules_assistant_chat_index;
  "modules/assistant/errors/index": typeof modules_assistant_errors_index;
  "modules/assistant/model/index": typeof modules_assistant_model_index;
  "modules/assistant/model/proposals": typeof modules_assistant_model_proposals;
  "modules/assistant/model/thread/access": typeof modules_assistant_model_thread_access;
  "modules/assistant/model/trip/context": typeof modules_assistant_model_trip_context;
  "modules/assistant/model/writes": typeof modules_assistant_model_writes;
  "modules/assistant/runs/functions": typeof modules_assistant_runs_functions;
  "modules/assistant/runs/index": typeof modules_assistant_runs_index;
  "modules/assistant/runs/tracking": typeof modules_assistant_runs_tracking;
  "modules/assistant/screen/index": typeof modules_assistant_screen_index;
  "modules/assistant/standalone/context": typeof modules_assistant_standalone_context;
  "modules/assistant/standalone/execute": typeof modules_assistant_standalone_execute;
  "modules/assistant/standalone/index": typeof modules_assistant_standalone_index;
  "modules/assistant/standalone/session": typeof modules_assistant_standalone_session;
  "modules/assistant/validators/index": typeof modules_assistant_validators_index;
  "modules/auth/auth": typeof modules_auth_auth;
  "modules/auth/workspace": typeof modules_auth_workspace;
  "modules/dev/local": typeof modules_dev_local;
  "modules/dev/populate": typeof modules_dev_populate;
  "modules/dev/reset": typeof modules_dev_reset;
  "modules/dev/targets": typeof modules_dev_targets;
  "modules/dev/trips": typeof modules_dev_trips;
  "modules/discussions/assistant/index": typeof modules_discussions_assistant_index;
  "modules/discussions/assistant/respond": typeof modules_discussions_assistant_respond;
  "modules/discussions/media/index": typeof modules_discussions_media_index;
  "modules/discussions/messages/index": typeof modules_discussions_messages_index;
  "modules/discussions/threads/cleanup": typeof modules_discussions_threads_cleanup;
  "modules/discussions/threads/entity": typeof modules_discussions_threads_entity;
  "modules/discussions/threads/index": typeof modules_discussions_threads_index;
  "modules/discussions/threads/limits": typeof modules_discussions_threads_limits;
  "modules/media/attachments/index": typeof modules_media_attachments_index;
  "modules/media/files/index": typeof modules_media_files_index;
  "modules/media/library/commit": typeof modules_media_library_commit;
  "modules/media/library/index": typeof modules_media_library_index;
  "modules/media/library/validators": typeof modules_media_library_validators;
  "modules/notifications/index": typeof modules_notifications_index;
  "modules/organizations/cleanup": typeof modules_organizations_cleanup;
  "modules/organizations/invitations/index": typeof modules_organizations_invitations_index;
  "modules/references/index": typeof modules_references_index;
  "modules/travel/activities/index": typeof modules_travel_activities_index;
  "modules/travel/activities/timeblocks": typeof modules_travel_activities_timeblocks;
  "modules/travel/covers/destination/index": typeof modules_travel_covers_destination_index;
  "modules/travel/covers/destination/stock": typeof modules_travel_covers_destination_stock;
  "modules/travel/covers/index": typeof modules_travel_covers_index;
  "modules/travel/covers/stock": typeof modules_travel_covers_stock;
  "modules/travel/destinations/index": typeof modules_travel_destinations_index;
  "modules/travel/issues/index": typeof modules_travel_issues_index;
  "modules/travel/issues/rewrite": typeof modules_travel_issues_rewrite;
  "modules/travel/locations/index": typeof modules_travel_locations_index;
  "modules/travel/locations/query": typeof modules_travel_locations_query;
  "modules/travel/packing/apply": typeof modules_travel_packing_apply;
  "modules/travel/packing/index": typeof modules_travel_packing_index;
  "modules/travel/packing/writes": typeof modules_travel_packing_writes;
  "modules/travel/preferences/index": typeof modules_travel_preferences_index;
  "modules/travel/stays/index": typeof modules_travel_stays_index;
  "modules/travel/targets/costkinds": typeof modules_travel_targets_costkinds;
  "modules/travel/targets/index": typeof modules_travel_targets_index;
  "modules/travel/targets/kind": typeof modules_travel_targets_kind;
  "modules/travel/targets/kinds/activity/index": typeof modules_travel_targets_kinds_activity_index;
  "modules/travel/targets/kinds/activity/transfer": typeof modules_travel_targets_kinds_activity_transfer;
  "modules/travel/targets/kinds/attachment/index": typeof modules_travel_targets_kinds_attachment_index;
  "modules/travel/targets/kinds/boundary/transfer": typeof modules_travel_targets_kinds_boundary_transfer;
  "modules/travel/targets/kinds/destination/index": typeof modules_travel_targets_kinds_destination_index;
  "modules/travel/targets/kinds/destination/transfer": typeof modules_travel_targets_kinds_destination_transfer;
  "modules/travel/targets/kinds/index": typeof modules_travel_targets_kinds_index;
  "modules/travel/targets/kinds/stay/index": typeof modules_travel_targets_kinds_stay_index;
  "modules/travel/targets/kinds/trip/index": typeof modules_travel_targets_kinds_trip_index;
  "modules/travel/transfers/index": typeof modules_travel_transfers_index;
  "modules/travel/travelers/index": typeof modules_travel_travelers_index;
  "modules/travel/trips/access": typeof modules_travel_trips_access;
  "modules/travel/trips/commit": typeof modules_travel_trips_commit;
  "modules/travel/trips/costs": typeof modules_travel_trips_costs;
  "modules/travel/trips/ctx": typeof modules_travel_trips_ctx;
  "modules/travel/trips/currencies": typeof modules_travel_trips_currencies;
  "modules/travel/trips/datetime": typeof modules_travel_trips_datetime;
  "modules/travel/trips/index": typeof modules_travel_trips_index;
  "modules/travel/trips/itinerary/fields": typeof modules_travel_trips_itinerary_fields;
  "modules/travel/trips/list": typeof modules_travel_trips_list;
  "modules/travel/trips/normalize": typeof modules_travel_trips_normalize;
  "modules/travel/trips/projection": typeof modules_travel_trips_projection;
  "modules/travel/versions/agent/review/action": typeof modules_travel_versions_agent_review_action;
  "modules/travel/versions/agent/review/index": typeof modules_travel_versions_agent_review_index;
  "modules/travel/versions/agent/title/action": typeof modules_travel_versions_agent_title_action;
  "modules/travel/versions/agent/title/index": typeof modules_travel_versions_agent_title_index;
  "modules/travel/versions/apply": typeof modules_travel_versions_apply;
  "modules/travel/versions/clone": typeof modules_travel_versions_clone;
  "modules/travel/versions/content": typeof modules_travel_versions_content;
  "modules/travel/versions/detailrebase": typeof modules_travel_versions_detailrebase;
  "modules/travel/versions/detailresolution": typeof modules_travel_versions_detailresolution;
  "modules/travel/versions/diff": typeof modules_travel_versions_diff;
  "modules/travel/versions/errors": typeof modules_travel_versions_errors;
  "modules/travel/versions/fields/index": typeof modules_travel_versions_fields_index;
  "modules/travel/versions/git/action": typeof modules_travel_versions_git_action;
  "modules/travel/versions/git/index": typeof modules_travel_versions_git_index;
  "modules/travel/versions/index": typeof modules_travel_versions_index;
  "modules/travel/versions/merge/action": typeof modules_travel_versions_merge_action;
  "modules/travel/versions/names": typeof modules_travel_versions_names;
  "modules/travel/versions/presentation": typeof modules_travel_versions_presentation;
  "modules/travel/versions/resolution": typeof modules_travel_versions_resolution;
  "modules/travel/versions/settings": typeof modules_travel_versions_settings;
  "modules/travel/versions/snapshot/format": typeof modules_travel_versions_snapshot_format;
  "modules/travel/versions/snapshot/index": typeof modules_travel_versions_snapshot_index;
  "modules/travel/versions/snapshot/types": typeof modules_travel_versions_snapshot_types;
  "modules/travel/versions/validators": typeof modules_travel_versions_validators;
  "modules/travel/versions/workflow": typeof modules_travel_versions_workflow;
  "routes/agents/get": typeof routes_agents_get;
  "routes/agents/issues": typeof routes_agents_issues;
  "routes/agents/list": typeof routes_agents_list;
  "routes/agents/runs/events": typeof routes_agents_runs_events;
  "routes/agents/runs/get": typeof routes_agents_runs_get;
  "routes/agents/runs/issue": typeof routes_agents_runs_issue;
  "routes/agents/runs/list": typeof routes_agents_runs_list;
  "routes/agents/runs/retry": typeof routes_agents_runs_retry;
  "routes/agents/runs/start": typeof routes_agents_runs_start;
  "routes/agents/runs/stop": typeof routes_agents_runs_stop;
  "routes/agents/runs/workspace": typeof routes_agents_runs_workspace;
  "routes/assistant/chats/create": typeof routes_assistant_chats_create;
  "routes/assistant/chats/list": typeof routes_assistant_chats_list;
  "routes/assistant/chats/tags": typeof routes_assistant_chats_tags;
  "routes/assistant/context/catalog": typeof routes_assistant_context_catalog;
  "routes/assistant/context/screen": typeof routes_assistant_context_screen;
  "routes/assistant/messages": typeof routes_assistant_messages;
  "routes/assistant/open": typeof routes_assistant_open;
  "routes/assistant/resend": typeof routes_assistant_resend;
  "routes/assistant/send": typeof routes_assistant_send;
  "routes/assistant/stop": typeof routes_assistant_stop;
  "routes/dev/reset": typeof routes_dev_reset;
  "routes/discussions/create": typeof routes_discussions_create;
  "routes/discussions/list": typeof routes_discussions_list;
  "routes/discussions/mark/read": typeof routes_discussions_mark_read;
  "routes/discussions/messages/attachments": typeof routes_discussions_messages_attachments;
  "routes/discussions/messages/edit": typeof routes_discussions_messages_edit;
  "routes/discussions/messages/list": typeof routes_discussions_messages_list;
  "routes/discussions/messages/react": typeof routes_discussions_messages_react;
  "routes/discussions/messages/reactions": typeof routes_discussions_messages_reactions;
  "routes/discussions/messages/remove": typeof routes_discussions_messages_remove;
  "routes/discussions/messages/respond": typeof routes_discussions_messages_respond;
  "routes/discussions/messages/send": typeof routes_discussions_messages_send;
  "routes/discussions/messages/stop": typeof routes_discussions_messages_stop;
  "routes/discussions/rename": typeof routes_discussions_rename;
  "routes/discussions/roster": typeof routes_discussions_roster;
  "routes/media/list": typeof routes_media_list;
  "routes/media/logo/clear": typeof routes_media_logo_clear;
  "routes/media/logo/set": typeof routes_media_logo_set;
  "routes/media/remove": typeof routes_media_remove;
  "routes/media/save": typeof routes_media_save;
  "routes/media/upload": typeof routes_media_upload;
  "routes/notifications/list": typeof routes_notifications_list;
  "routes/notifications/mark/all": typeof routes_notifications_mark_all;
  "routes/notifications/mark/read": typeof routes_notifications_mark_read;
  "routes/organizations/invitations/create": typeof routes_organizations_invitations_create;
  "routes/organizations/invitations/list": typeof routes_organizations_invitations_list;
  "routes/organizations/invitations/redeem": typeof routes_organizations_invitations_redeem;
  "routes/organizations/invitations/revoke": typeof routes_organizations_invitations_revoke;
  "routes/references/resolve": typeof routes_references_resolve;
  "routes/settings/ai/get": typeof routes_settings_ai_get;
  "routes/settings/ai/set": typeof routes_settings_ai_set;
  "routes/settings/reviews/get": typeof routes_settings_reviews_get;
  "routes/settings/reviews/set": typeof routes_settings_reviews_set;
  "routes/trips/archive": typeof routes_trips_archive;
  "routes/trips/attachments/list": typeof routes_trips_attachments_list;
  "routes/trips/attachments/set": typeof routes_trips_attachments_set;
  "routes/trips/cover": typeof routes_trips_cover;
  "routes/trips/cover/retry": typeof routes_trips_cover_retry;
  "routes/trips/covers/ensure": typeof routes_trips_covers_ensure;
  "routes/trips/create": typeof routes_trips_create;
  "routes/trips/destinations/activities/add": typeof routes_trips_destinations_activities_add;
  "routes/trips/destinations/activities/remove": typeof routes_trips_destinations_activities_remove;
  "routes/trips/destinations/activities/reorder": typeof routes_trips_destinations_activities_reorder;
  "routes/trips/destinations/activities/transfers/remove": typeof routes_trips_destinations_activities_transfers_remove;
  "routes/trips/destinations/activities/transfers/set": typeof routes_trips_destinations_activities_transfers_set;
  "routes/trips/destinations/activities/update": typeof routes_trips_destinations_activities_update;
  "routes/trips/destinations/add": typeof routes_trips_destinations_add;
  "routes/trips/destinations/covers/ensure": typeof routes_trips_destinations_covers_ensure;
  "routes/trips/destinations/move": typeof routes_trips_destinations_move;
  "routes/trips/destinations/remove": typeof routes_trips_destinations_remove;
  "routes/trips/destinations/stays/add": typeof routes_trips_destinations_stays_add;
  "routes/trips/destinations/stays/remove": typeof routes_trips_destinations_stays_remove;
  "routes/trips/destinations/stays/update": typeof routes_trips_destinations_stays_update;
  "routes/trips/destinations/transfers/remove": typeof routes_trips_destinations_transfers_remove;
  "routes/trips/destinations/transfers/set": typeof routes_trips_destinations_transfers_set;
  "routes/trips/destinations/update": typeof routes_trips_destinations_update;
  "routes/trips/find": typeof routes_trips_find;
  "routes/trips/get": typeof routes_trips_get;
  "routes/trips/issues/assign": typeof routes_trips_issues_assign;
  "routes/trips/issues/comment": typeof routes_trips_issues_comment;
  "routes/trips/issues/create": typeof routes_trips_issues_create;
  "routes/trips/issues/due": typeof routes_trips_issues_due;
  "routes/trips/issues/get": typeof routes_trips_issues_get;
  "routes/trips/issues/list": typeof routes_trips_issues_list;
  "routes/trips/issues/status": typeof routes_trips_issues_status;
  "routes/trips/issues/workspace/list": typeof routes_trips_issues_workspace_list;
  "routes/trips/list": typeof routes_trips_list;
  "routes/trips/locations/nearest": typeof routes_trips_locations_nearest;
  "routes/trips/locations/region": typeof routes_trips_locations_region;
  "routes/trips/packing/add": typeof routes_trips_packing_add;
  "routes/trips/packing/list": typeof routes_trips_packing_list;
  "routes/trips/packing/remove": typeof routes_trips_packing_remove;
  "routes/trips/packing/update": typeof routes_trips_packing_update;
  "routes/trips/preferences/favorite": typeof routes_trips_preferences_favorite;
  "routes/trips/restore": typeof routes_trips_restore;
  "routes/trips/seed/populate": typeof routes_trips_seed_populate;
  "routes/trips/seed/workspace": typeof routes_trips_seed_workspace;
  "routes/trips/transfers/remove": typeof routes_trips_transfers_remove;
  "routes/trips/transfers/set": typeof routes_trips_transfers_set;
  "routes/trips/travelers/claim": typeof routes_trips_travelers_claim;
  "routes/trips/travelers/list": typeof routes_trips_travelers_list;
  "routes/trips/travelers/set": typeof routes_trips_travelers_set;
  "routes/trips/update": typeof routes_trips_update;
  "routes/trips/upload": typeof routes_trips_upload;
  "routes/trips/versions/approval": typeof routes_trips_versions_approval;
  "routes/trips/versions/close": typeof routes_trips_versions_close;
  "routes/trips/versions/create": typeof routes_trips_versions_create;
  "routes/trips/versions/details/resolve": typeof routes_trips_versions_details_resolve;
  "routes/trips/versions/feedback/add": typeof routes_trips_versions_feedback_add;
  "routes/trips/versions/feedback/list": typeof routes_trips_versions_feedback_list;
  "routes/trips/versions/feedback/resolve": typeof routes_trips_versions_feedback_resolve;
  "routes/trips/versions/get": typeof routes_trips_versions_get;
  "routes/trips/versions/list": typeof routes_trips_versions_list;
  "routes/trips/versions/merge": typeof routes_trips_versions_merge;
  "routes/trips/versions/rebase": typeof routes_trips_versions_rebase;
  "routes/trips/versions/resolve": typeof routes_trips_versions_resolve;
  "routes/trips/versions/reviewers/agent/run": typeof routes_trips_versions_reviewers_agent_run;
  "routes/trips/versions/reviewers/set": typeof routes_trips_versions_reviewers_set;
  "routes/trips/versions/submit": typeof routes_trips_versions_submit;
  "routes/trips/versions/workspace/list": typeof routes_trips_versions_workspace_list;
  "routes/trips/versions/workspace/pending": typeof routes_trips_versions_workspace_pending;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../components/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  geospatial: import("@convex-dev/geospatial/_generated/component.js").ComponentApi<"geospatial">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  web: import("@convex-dev/static-hosting/_generated/component.js").ComponentApi<"web">;
};
